---
- name: Converge
  hosts: all

  vars_files: vars.yml

  roles:

    - role: geerlingguy.repo-epel
    - role: geerlingguy.apache
    - role: cloudweeb.php
    - role: cloudweeb.mariadb
    - role: cloudweeb.librenms
