---

librenms_db_pass: "{{ lookup('password',
                            '/tmp/passwordfile
                            chars=ascii_letters,digits,hexdigits,punctuation'
                            ) }}"

apache_vhosts:
  - servername: librenms.example.com
    documentroot: /opt/librenms/html/
    extra_parameters: |
      AllowEncodedSlashes NoDecode

php_version: 7.2

php_extra_packages:
  - composer
  - php-mysqlnd
  - php-curl
  - php-gd
  - php-mbstring
  - php-process
  - php-snmp
  - php-xml
  - php-zip

mariadb_root_password: "{{ lookup('password', '/tmp/mysql_root_password
                                length=15
                                chars=ascii_letters,digits,hexdigits') }}"
